-- MySQL Script generated by MySQL Workbench
-- mié 13 abr 2016 10:49:08 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GITKRAKEN_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GITKRAKEN_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GITKRAKEN_DB` DEFAULT CHARACTER SET latin1 ;
USE `GITKRAKEN_DB` ;

-- -----------------------------------------------------
-- Table `GITKRAKEN_DB`.`RANKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GITKRAKEN_DB`.`RANKING` (
  `NICK` VARCHAR(10) NOT NULL,
  `SCORE` INT(11) NOT NULL,
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GITKRAKEN_DB`.`ESTADISTICAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GITKRAKEN_DB`.`ESTADISTICAS` (
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CANTIDAD` BIGINT(10) NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  PRIMARY KEY (`NOMBRE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GITKRAKEN_DB`.`RANKING_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GITKRAKEN_DB`.`RANKING_copy1` (
  `NICK` VARCHAR(10) NOT NULL,
  `SCORE` INT(11) NOT NULL,
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `GITKRAKEN_DB`.`ESTADISTICAS`
-- -----------------------------------------------------
START TRANSACTION;
USE `GITKRAKEN_DB`;
INSERT INTO `GITKRAKEN_DB`.`ESTADISTICAS` (`NOMBRE`, `CANTIDAD`, `DESCRIPCION`) VALUES ('PARTIDAS', 0, 'Total de partidas Jugadas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `GITKRAKEN_DB`.`RANKING_copy1`
-- -----------------------------------------------------
START TRANSACTION;
USE `GITKRAKEN_DB`;
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);
INSERT INTO `GITKRAKEN_DB`.`RANKING_copy1` (`NICK`, `SCORE`, `ID`) VALUES ('---------', 0, DEFAULT);

COMMIT;

